version: "3.8"
services:
  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lulabs_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
